# Generated by Django 3.1.2 on 2020-12-31 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
